// Curriculum index mapping strictly to CBSE Class 12 (2026-27)
export const demoCurriculum = {
  mathematics: {
    id: 'mathematics',
    title: 'Mathematics (041)',
    chapters: [
      'Relations and Functions',
      'Inverse Trigonometric Functions',
      'Matrices',
      'Determinants',
      'Continuity and Differentiability',
      'Applications of Derivatives',
      'Integrals',
      'Applications of Integrals',
      'Differential Equations',
      'Vectors',
      'Three-Dimensional Geometry',
      'Linear Programming',
      'Probability',
    ],
  },
  physics: {
    id: 'physics',
    title: 'Physics (042)',
    chapters: [
      'Electric Charges and Fields',
      'Electrostatic Potential and Capacitance',
      'Current Electricity',
      'Moving Charges and Magnetism',
      'Magnetism and Matter',
      'Electromagnetic Induction',
      'Alternating Current',
      'Electromagnetic Waves',
      'Ray Optics and Optical Instruments',
      'Wave Optics',
      'Dual Nature of Radiation and Matter',
      'Atoms',
      'Nuclei',
      'Semiconductor Electronics',
    ],
  },
  chemistry: {
    id: 'chemistry',
    title: 'Chemistry (043)',
    chapters: [
      'Solutions',
      'Electrochemistry',
      'Chemical Kinetics',
      'd- and f-Block Elements',
      'Coordination Compounds',
      'Haloalkanes and Haloarenes',
      'Alcohols, Phenols and Ethers',
      'Aldehydes, Ketones and Carboxylic Acids',
      'Amines',
      'Biomolecules',
    ],
  },
  english: {
    id: 'english',
    title: 'English Core (301)',
    sections: ['Reading Skills', 'Creative Writing Skills', 'Literature Textbooks (Flamingo & Vistas)'],
  },
};
